# -*- coding: utf-8 -*-
"""DSBP_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NBG3q8awhmWealDQexRSDNyzI5JvmQ7
"""
# if this is your first time using a module, you'll need to install it with: pip install <module_name>
# pip install matplotlib
import os
import pandas as pd
import matplotlib.pyplot as plt

#Renaming files 
# Set directory path where your file is located.
directory = r'C:/Users/clee1/OneDrive - Fors Marsh/Desktop/FEVS'

# Simple example renaming file /rename your own file
old_filename = 'FEVS_2023_PRDF.csv' # Define the current name of the file you want to rename / Replace with the actual file name
new_filename = 'FEVS_2023_PRDF_renamed.csv' # Define then new name you want the file to have / Replace with the desired file name

#Option 1

# Rename the file directory using os.path.join to combine paths
# old_file_path = os.path.join(directory, old_filename)
# new_file_path = os.path.join(directory, new_filename)

# Rename the directory using os.resume
# os.rename(old_file_path, new_file_path)

#Option 2
os.rename(os.path.join(directory, old_filename), os.path.join(directory, new_filename))

#Print confirmation
print(f'Renamed {old_filename} to {new_filename}')


"""
If you want to explore more, here are more examples you can play with
"""

#Print string
print ("Hello A-G!")

#If-Else Statement
AG_employee = input("Are you in A-G Team? (yes/no): ").lower()

if AG_employee == "yes":
  print("Welcome to A-G!")
else:
  print("You are not in A-G Team.")

#Reading csv file
df = pd.read_csv(r'fevs_2016_prdf.csv')

print(df.head())

#Filtering Data - OR operator
myDictionary = {'Name' : ['Chae', 'Madison', "Lara"],
                'Age' : [10, 11, 12],
                'State' : ['VA', 'MD', "DC"]}

df = pd.DataFrame(myDictionary)

filtered_or = df[(df['Age'] >10 )| (df['State'] == 'MD')]

print(filtered_or)

#Filtering Data - AND operator
myDictionary = {'Name' : ['Chae', 'Madison', "Lara"],
                'Age' : [10, 11, 12],
                'State' : ['VA', 'MD', "DC"]}

df = pd.DataFrame(myDictionary)

filtered_and = df[(df['Age'] > 10) & (df['State'] == 'DC')]

print(filtered_and)

"""Data Visualization - Histogram"""
# Sample DataFrame
data = {'Age': [25, 30, 35, 40, 45, 50, 55, 60]}
df = pd.DataFrame(data)

# Plot a histogram of the 'Age' column
df['Age'].plot(kind='hist', bins=3, color='pink', edgecolor='purple')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

"""Data Visualization - Line Plot"""
# Sample DataFrame
data = {'Year': [2020, 2021, 2022, 2023, 2024],
        'Employee': [10, 15, 20, 55, 300]}
df = pd.DataFrame(data)

# Line plot of Revenue over years
df.plot(x='Year', y='Employee', kind='line', marker='o', color='green')
plt.title('Company Employee Over Time')
plt.xlabel('Year')
plt.ylabel('Employee')
plt.show()
